dist: xenial

language: generic

cache:
  directories:
    - /opt/cabal
    - /opt/ghc
    - $HOME/.cabal
    - dist-newstyle

install:
  - sudo add-apt-repository --yes ppa:hvr/ghc
  - sudo apt-get update
  - export GHC=8.6.4 CABAL=2.4
  - export PATH="/opt/ghc/$GHC/bin:/opt/cabal/$CABAL/bin:$PATH"
  - which ghc || sudo apt-get install "ghc-$GHC"
  - which cabal || sudo apt-get install "cabal-install-$CABAL"
  - cabal v2-update
  - cabal v2-build --only-dependencies

script:
  - cabal v2-build
  - cabal v2-exec podcast

deploy:
  github-token: $GITHUB_TOKEN
  local-dir: site
  on:
    branch: master
  provider: pages
  skip-cleanup: true
