dist: xenial

language: generic

install:
  - sudo add-apt-repository --yes ppa:hvr/ghc
  - sudo apt-get update
  - export GHC=8.6.4 CABAL=2.4
  - sudo apt-get install "ghc-$GHC" "cabal-install-$CABAL"
  - export PATH="/opt/ghc/$GHC/bin:/opt/cabal/$CABAL/bin:$PATH"
  - cabal v2-update
  - cabal v2-build --only-dependencies

script:
  - cabal v2-build
  - cabal v2-exec podcast
