dist: xenial

language: generic

install:
  - sudo add-apt-repository --yes ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install cabal-install-2.4 ghc-8.6.4
  - cabal v2-update
  - cabal v2-build --only-dependencies

script:
  - cabal v2-build
  - cabal v2-exec podcast
