dist: xenial

language: haskell

install:
  - cabal update
  - cabal install --only-dependencies

script:
  - cabal build
  - cabal exec podcast

deploy:
  github-token: $GITHUB_TOKEN
  local-dir: output
  on:
    branch: master
  provider: pages
  skip-cleanup: true
