dist: xenial

language: generic

addons:
  apt:
    sources:
      - ppa:hvr/ghc
    packages:
      - cabal-install-2.4
      - ghc-8.6.4

install:
  - cabal v2-update
  - cabal v2-build --only-dependencies

script:
  - cabal v2-build
  - cabal v2-exec podcast
