name: podcast
version: 0

dependencies:
  - base
  - bytestring
  - containers
  - directory
  - filepath
  - network-uri
  - template-haskell
  - text
  - time
  - uuid
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-exported-signatures
  - -Wno-safe
  - -Wno-unsafe

library:
  exposed-modules: Podcast.Main
  source-dirs: source/library

executable:
  dependencies: podcast
  ghc-options:
    - -optP -Wno-nonportable-include-path
    - -rtsopts
    - -threaded
  main: Main.hs
  source-dirs: source/executable
